name: Run tests

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
  workflow_dispatch:

env:
  PACKAGE_VERSION: "1.0.${{ github.run_number }}"
  IMAGE_RELEASE: "v1.0.0-test"
  USER: 'cpintado'
  OWNER: 'cpintado-org'
  REPOSITORY: 'test-packages'
  ARTIFACT_ID: 'cpintado-org-test-package'
  GROUP_ID: 'com.github.cpintadoorg'

jobs:
  test-publish-dotcom:
    runs-on: ubuntu-latest
    name: Publish a package to github.com
    env:
      TOKEN: ${{ secrets.GHEC_PAT }}
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:$IMAGE_RELEASE
    - name: Publish a package
      run: |
        docker run -e USER -e TOKEN \
        -e OWNER -e REPOSITORY
        -e ARTIFACT_ID -e GROUP_ID -e PACKAGE_VERSION \
        ghcr.io/${{ github.repository }}:$IMAGE_RELEASE
  test-publish-ghes-subdomain:
    runs-on: ubuntu-latest
    name: Publish a package to a GHES instance with subdomain isolation enabled
    env:
      TOKEN: ${{ secrets.GHES_PAT }}
      GHES_HOSTNAME: ${{ vars.GHES_INSTANCE }}
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:$IMAGE_RELEASE
    - name: Publish a package
      run: |
        docker run -e USER -e TOKEN \
        -e OWNER -e REPOSITORY
        -e ARTIFACT_ID -e GROUP_ID -e PACKAGE_VERSION \
        -e GHES_HOSTNAME \
        ghcr.io/${{ github.repository }}:$IMAGE_RELEASE
  test-publish-ghes-subdomain-disabled:
    runs-on: ubuntu-latest
    name: Publish a package to a GHES instance with subdomain isolation disabled
    env:
      TOKEN: ${{ secrets.GHES_PAT_NO_SUBDOMAIN }}
      GHES_HOSTNAME: ${{ vars.GHES_INSTANCE_NO_SUBDOMAIN }}
      SUBDOMAIN_ISOLATION: false
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:$IMAGE_RELEASE
    - name: Publish a package
      run: |
        docker run -e USER -e TOKEN \
        -e OWNER -e REPOSITORY
        -e ARTIFACT_ID -e GROUP_ID -e PACKAGE_VERSION \
        -e GHES_HOSTNAME -e SUBDOMAIN_ISOLATION \
        ghcr.io/${{ github.repository }}:$IMAGE_RELEASE
